<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiculoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Categorias
        DB::table('categorias')->insert([
            'nombre'=>('Citicar')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Sedan')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Deportivo')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Camioneta')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Comercial')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Van')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Suvs')
        ]);
        DB::table('categorias')->insert([
            'nombre'=>('Jeep')
        ]);
        //Marca
        DB::table('marcas')->insert([
            'nombre'=>('CHEVROLET')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('FIAT')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('NISSAN')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('TOYOTA')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('SUZUKI')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('HONDA')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('HYUNDAI')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('KIA')
        ]);
        DB::table('marcas')->insert([
            'nombre'=>('MAZDA')
        ]);
        //VEHICULOS
        DB::table('vehiculos')->insert([
            'nombre'=>('Cruze'),
            'precio'=>('14000'),
            'color'=>('Negro'),
            'año'=>('2014'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('1GNCS13Z6M0246591'),
            'categoria_id'=>('7'),
            'marca_id'=>('1'),
            'almacen_id'=>('1'),
        ]);
        DB::table('vehiculos')->insert([
            'nombre'=>('Panda'),
            'precio'=>('12000'),
            'color'=>('Blanco'),
            'año'=>('2018'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('6JJKS43K4M039483'),
            'categoria_id'=>('1'),
            'marca_id'=>('2'),
            'almacen_id'=>('2'),
        ]);
        DB::table('vehiculos')->insert([
            'nombre'=>('Accord'),
            'precio'=>('13500'),
            'color'=>('Plomo'),
            'año'=>('2018'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('9JKLD83K0J289028'),
            'categoria_id'=>('2'),
            'marca_id'=>('6'),
            'almacen_id'=>('1'),
        ]);
        DB::table('vehiculos')->insert([
            'nombre'=>('Civic Touring'),
            'precio'=>('25000'),
            'color'=>('Negro'),
            'año'=>('2021'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('7JSKL73J8J3789403'),
            'categoria_id'=>('3'),
            'marca_id'=>('6'),
            'almacen_id'=>('1'),
        ]);
        DB::table('vehiculos')->insert([
            'nombre'=>('frontier'),
            'precio'=>('26000'),
            'color'=>('Rojo'),
            'año'=>('2021'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('7JKSL83H4J4789389'),
            'categoria_id'=>('4'),
            'marca_id'=>('3'),
            'almacen_id'=>('1'),
        ]);
        DB::table('vehiculos')->insert([
            'nombre'=>('370Z'),
            'precio'=>('34000'),
            'color'=>('Blanco'),
            'año'=>('2020'),
            'estado'=>('ingresado'),
            'nro_chasis'=>('8HJJK34G4E7489047'),
            'categoria_id'=>('3'),
            'marca_id'=>('3'),
            'almacen_id'=>('1'),
        ]);
    }
}
